version: "3.8"

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: pg_duplo_go_raincloud
      POSTGRES_USER: mick
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
